function (create_test_and_nontest)
    set(options)
    set(oneValueArgs NAME)
    set(multipleValueArgs FILE_SRCS LIBRARIES INCLUDE_DIR)

    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multipleValueArgs}" ${ARGN})

    set(LIB_NAME ${ARG_NAME})
    set(LIB_SRCS ${ARG_FILE_SRCS})
    set(LIB_LIBRARIES ${ARG_LIBRARIES})
    set(LIB_INCLUDE_DIR ${ARG_INCLUDE_DIR})

    set(LIBTEST_NAME "${ARG_NAME}-test")
    set(LIBTEST_SRCS ${ARG_FILE_SRCS})
    list(TRANSFORM ARG_LIBRARIES APPEND "-test" OUTPUT_VARIABLE LIBTEST_LIBRARIES)
    set(LIBTEST_INCLUDE_DIR ${ARG_INCLUDE_DIR})

    add_library(${LIB_NAME} STATIC ${LIB_SRCS})
    target_include_directories(${LIB_NAME} PRIVATE ${LIB_INCLUDE_DIR})
    target_link_libraries(${LIB_NAME} PUBLIC ${LIB_LIBRARIES})
    target_compile_options(${LIB_NAME} PRIVATE ${KFLAGS})
    set_target_properties(${LIB_NAME} PROPERTIES CMAKE_CXX_COMPILER ${CXX_CROSS_COMPILER})

    add_library(${LIBTEST_NAME} STATIC ${LIBTEST_SRCS})
    target_include_directories(${LIBTEST_NAME} PRIVATE ${LIBTEST_INCLUDE_DIR})
    target_link_libraries(${LIBTEST_NAME} PUBLIC ${LIBTEST_LIBRARIES})
    target_compile_options(${LIBTEST_NAME} PRIVATE ${KFLAGS})
    target_compile_definitions(${LIBTEST_NAME} PRIVATE KFS_HOST_TEST)
    set_target_properties(${LIBTEST_NAME} PROPERTIES CMAKE_CXX_COMPILER ${CXX_CROSS_COMPILER})
endfunction()

add_subdirectory(container)
add_subdirectory(format)
add_subdirectory(logging)
add_subdirectory(math)
add_subdirectory(str)
add_subdirectory(port)
add_subdirectory(vga)
add_subdirectory(keyboard)