---
config:
    themeVariables:
        treeView:
            labelColor: 'black'
            lineColor: 'black'
        background: 'transparent'
---
treeView-beta
    "github/"       ## contain github actions
    "docker"        ## contain docker containers and entrypoints
    "documentation" ## contain the documentation
    "src"           ## project sources
        "core"      ## some defs
        "include"   ## some defs
        "lib"       ## all library and drivers
    "tests"         ## project tests