---
config:
    themeVariables:
        treeView:
            labelColor: 'black'
            lineColor: 'black'
---
treeView-beta
    "github"       ## contain github actions (1)
    "docker"        ## contain docker containers and entrypoints (2)
    "documentation" ## contain the documentation (3)
    "src"           ## project sources (4)
        "core"      ## Sources of the kernel itself (4.1)
        "include"   ## some defs (4.2)
        "lib"       ## kernel libraries (4.3)
        "drivers"   ## kernel drivers (4.4)